### ISSUE TITLE
Deflection Belt kicks player on server when worn

### ISSUE THREAD

**Issue by belathus** [BrassGoggledCoders/ModularUtilities#10]
As you know, we're on the 1.10 version of Modular Utilities. Here is the console's report when the player tries to join the server after wearing the belt:

`java.lang.NoSuchMethodError: net.minecraft.entity.Entity.func_70016_h(DDD)V
    at xyz.brassgoggledcoders.modularutilities.modules.baubles.ItemDeflectionBelt.onWornTick(ItemDeflectionBelt.java:39) ~[ItemDeflectionBelt.class:?]
    at baubles.common.event.EventHandlerEntity.playerTick(EventHandlerEntity.java:113) ~[EventHandlerEntity.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_195_EventHandlerEntity_playerTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:493) [ForgeHooks.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70071h(EntityLivingBase.java:1931) [sf.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_70071h(EntityPlayer.java:233) [zs.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) [lu.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) [me.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]`

**Comment by SkySom** [comment]
Fixed in all versions
